/*
 * clk.c
 *
 * Created: 07/09/2016 20:02:49
 *  Author: Jon
 */ 
#include "clk.h"
#include "pio.h"

#define NVM_DFLL48M_COARSE_CAL_POS   58
#define NVM_DFLL48M_COARSE_CAL_SIZE  6

#define NVM_DFLL48M_FINE_CAL_POS     64
#define NVM_DFLL48M_FINE_CAL_SIZE    10


#define NVM_READ_CAL(cal) \
	((*((uint32_t *)cal##_ADDR) & cal##_Msk) >> cal##_Pos)

void CLK_Init(void)
{
	SYSCTRL->OSC8M.bit.PRESC = 0;
	
    // Setup XOSC32K for external crystal oscillator 32768 Hz
    SYSCTRL->XOSC32K.reg = SYSCTRL_XOSC32K_STARTUP(3) |	SYSCTRL_XOSC32K_XTALEN | SYSCTRL_XOSC32K_EN32K;
    SYSCTRL->XOSC32K.bit.ENABLE = 1;
    while (!SYSCTRL->PCLKSR.bit.XOSC32KRDY);

    // GCLK2 at 32768 Hz
    GCLK->GENDIV.reg = GCLK_GENDIV_ID(2) | GCLK_GENDIV_DIV(1);
    GCLK->GENCTRL.reg = GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_XOSC32K | GCLK_GENCTRL_ID(2);
	
    // Provide DFLL48M reference from GCLK2
    GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK2 | GCLK_CLKCTRL_ID_DFLL48;

    // Setup DFLL48M
    SYSCTRL->DFLLCTRL.reg = SYSCTRL_DFLLCTRL_ENABLE;
	while (!SYSCTRL->PCLKSR.bit.DFLLRDY);
    SYSCTRL->DFLLMUL.reg = SYSCTRL_DFLLMUL_CSTEP(31) | SYSCTRL_DFLLMUL_FSTEP(511) | SYSCTRL_DFLLMUL_MUL(1464);
	SYSCTRL->DFLLVAL.reg = SYSCTRL_DFLLVAL_FINE(NVM_READ_CAL(FUSES_DFLL48M_FINE_CAL)) |
	                       SYSCTRL_DFLLVAL_COARSE(NVM_READ_CAL(FUSES_DFLL48M_COARSE_CAL));	                       
    SYSCTRL->DFLLCTRL.reg = SYSCTRL_DFLLCTRL_ENABLE | SYSCTRL_DFLLCTRL_MODE | SYSCTRL_DFLLCTRL_QLDIS;
	while (!SYSCTRL->PCLKSR.bit.DFLLLCKC || !SYSCTRL->PCLKSR.bit.DFLLLCKF);
	
    // Set wait state (1) for running the CPU at 48MHz
    NVMCTRL->CTRLB.bit.RWS = 1;
	
	// Use DFLL48M for GCLK0
	GCLK->GENDIV.reg = GCLK_GENDIV_ID(0) | GCLK_GENDIV_DIV(1);
	GCLK->GENCTRL.reg  = /*GCLK_GENCTRL_OE |*/ GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_DFLL48M | GCLK_GENCTRL_ID(0);
   
	// GCLK1 also using DFLL48M but divide by 48 for 1 MHz
	GCLK->GENDIV.reg = GCLK_GENDIV_ID(1) | GCLK_GENDIV_DIV(48);
	GCLK->GENCTRL.reg  = GCLK_GENCTRL_OE | GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_DFLL48M | GCLK_GENCTRL_ID(1);

	// GCLK3 from 32768 Hz but divide by 2^(3+1) for 2048 Hz
	GCLK->GENDIV.reg = GCLK_GENDIV_ID(3) | GCLK_GENDIV_DIV(3);
    GCLK->GENCTRL.reg = /*GCLK_GENCTRL_OE |*/ GCLK_GENCTRL_GENEN | GCLK_GENCTRL_DIVSEL | GCLK_GENCTRL_SRC_XOSC32K | GCLK_GENCTRL_ID(3);
}

void CLK_EnablePeripheral(uint8_t ClkGen, uint8_t PerCh)
{
	GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN(ClkGen) | PerCh;
}
